AwsExplorer/AwsExplorer/Controllers/S3ObjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using AwsExplorer.Models;
using Amazon.S3;
using ICSharpCode.SharpZipLib.Zip;
using System.IO;

namespace AwsExplorer.Controllers
{
  public class S3ObjectController : Controller
  {
    private AwsEntities db = new AwsEntities();
    private AmazonS3 s3 = Amazon.AWSClientFactory.CreateAmazonS3Client(new AmazonS3Config());

    //
    // GET: /S3Object/

    public ActionResult Index(string prefix = "", int maxKeys = 100)
    {
      ViewBag.prefix = prefix;
      ViewBag.maxKeys = maxKeys;

      var list = new Amazon.S3.Model.ListObjectsRequest();
      list.WithBucketName(WebConfigurationManager.AppSettings["UploadBucket"]);
      if (!String.IsNullOrWhiteSpace(prefix))
      {
        list.WithPrefix(prefix);
      }

      list.WithMaxKeys(maxKeys);

      var response = s3.ListObjects(list);

      return View(response.S3Objects.Select(e => new S3Object
        {
          Key = e.Key,
          Size = e.Size,
          LastModified = e.LastModified
        }));
    }

    //
    // GET: /S3Object/Details/5

    public ActionResult Details(string id = null, string prefix = "", int maxKeys = 100)
    {
      ViewBag.prefix = prefix;
      ViewBag.maxKeys = maxKeys;

      var list = new Amazon.S3.Model.ListObjectsRequest();
      list.WithBucketName(WebConfigurationManager.AppSettings["UploadBucket"]);
      list.WithPrefix(id);

      var s3Objects = s3.ListObjects(list).S3Objects;
      if (s3Objects.Count == 0)
      {
        return HttpNotFound();
      }

      var get = new Amazon.S3.Model.GetObjectRequest();
      get.WithBucketName(WebConfigurationManager.AppSettings["UploadBucket"]);
      get.WithKey(s3Objects[0].Key);

      var response = s3.GetObject(get);

      S3Object modelObject = new S3Object
      {
        Key = s3Objects[0].Key,
        Size = s3Objects[0].Size,
        LastModified = s3Objects[0].LastModified,
        ContentType = response.ContentType
      };

      return View(modelObject);
    }

    //
    // GET: /S3Object/Create

    public ActionResult Create(string prefix = "", int maxKeys = 100)
    {
      ViewBag.prefix = prefix;
      ViewBag.maxKeys = maxKeys;

      return View();
    }

    //
    // POST: /S3Object/Create

    [HttpPost]
    public ActionResult Create(S3Object s3object, string prefix = "", int maxKeys = 100)
    {
      ViewBag.prefix = prefix;
      ViewBag.maxKeys = maxKeys;

      if (ModelState.IsValid && Request.Files.Count > 0)
      {
        var put = new Amazon.S3.Model.PutObjectRequest();
        put.WithBucketName(WebConfigurationManager.AppSettings["UploadBucket"]);
        put.WithKey(s3object.Key);

        var file = Request.Files[0];
        put.WithContentType(file.ContentType);
        put.WithInputStream(file.InputStream);
        put.WithCannedACL(Amazon.S3.Model.S3CannedACL.PublicRead);
        Amazon.S3.Model.PutObjectResponse result = s3.PutObject(put);

        return RedirectToAction("Index", new { prefix = prefix, maxKeys = maxKeys });
      }

      return View(s3object);
    }

    //
    // GET: /S3Object/BulkCreate
    public ActionResult BulkCreate(string prefix = "", int maxKeys = 100)
    {
      ViewBag.prefix = prefix;
      ViewBag.maxKeys = maxKeys;

      return View();
    }

    //
    // POST: /S3Object/BulkCreate

    [HttpPost, ActionName("BulkCreate")]
    public ActionResult BulkCreateConfirmed(string prefix = "", int maxKeys = 100)
    {
      ViewBag.prefix = prefix;
      ViewBag.maxKeys = maxKeys;

      byte[] buffer = new byte[4096];

      if (Request.Files.Count > 0)
      {
        try
        {
          using (var fileStream = Request.Files[0].InputStream)
          {
            ZipFile zf = new ZipFile(fileStream);

            foreach (ZipEntry zipEntry in zf)
            {
              if (!zipEntry.IsFile)
              {
                continue;
              }

              string entryFileName = zipEntry.Name;
              string entryKey = prefix + entryFileName;

              using (MemoryStream ms = new MemoryStream((int)zipEntry.Size))
              {
                ICSharpCode.SharpZipLib.Core.StreamUtils.Copy(zf.GetInputStream(zipEntry), ms, buffer);

                ms.Seek(0, SeekOrigin.Begin);

                var put = new Amazon.S3.Model.PutObjectRequest();
                put.WithBucketName(WebConfigurationManager.AppSettings["UploadBucket"]);
                put.WithCannedACL(Amazon.S3.Model.S3CannedACL.PublicRead);

                put.WithKey(entryKey);
                put.WithInputStream(ms);
                Amazon.S3.Model.PutObjectResponse result = s3.PutObject(put);

              }


            }
          }

          return RedirectToAction("Index", new { prefix = prefix, maxKeys = maxKeys });
        }
        catch (Exception ex)
        {
          Request.RequestContext.HttpContext.Trace.Write(ex.Message);
        }
      }

      return View();
    }

    //
    // GET: /S3Object/Edit/5

    public ActionResult Edit(string id = null, string prefix = "", int maxKeys = 100)
    {
      ViewBag.prefix = prefix;
      ViewBag.maxKeys = maxKeys;

      var list = new Amazon.S3.Model.ListObjectsRequest();
      list.WithBucketName(WebConfigurationManager.AppSettings["UploadBucket"]);
      list.WithPrefix(id);

      var s3Objects = s3.ListObjects(list).S3Objects;
      if (s3Objects.Count == 0)
      {
        return HttpNotFound();
      }

      var get = new Amazon.S3.Model.GetObjectRequest();
      get.WithBucketName(WebConfigurationManager.AppSettings["UploadBucket"]);
      get.WithKey(s3Objects[0].Key);

      var response = s3.GetObject(get);

      S3Object modelObject = new S3Object
      {
        Key = s3Objects[0].Key,
        Size = s3Objects[0].Size,
        LastModified = s3Objects[0].LastModified,
        ContentType = response.ContentType
      };

      return View(modelObject);
    }

    //
    // POST: /S3Object/Edit/5

    [HttpPost]
    public ActionResult Edit(S3Object s3object, string prefix = "", int maxKeys = 100)
    {
      ViewBag.prefix = prefix;
      ViewBag.maxKeys = maxKeys;

      if (ModelState.IsValid && Request.Files.Count > 0)
      {
        var put = new Amazon.S3.Model.PutObjectRequest();
        put.WithBucketName(WebConfigurationManager.AppSettings["UploadBucket"]);
        put.WithKey(s3object.Key);

        var file = Request.Files[0];
        put.WithContentType(file.ContentType);
        put.WithInputStream(file.InputStream);
        put.WithCannedACL(Amazon.S3.Model.S3CannedACL.PublicRead);
        s3.PutObject(put);

        return RedirectToAction("Index", new { prefix = prefix, maxKeys = maxKeys });
      }

      return View(s3object);
    }

    //
    // GET: /S3Object/Delete/5

    public ActionResult Delete(string id = null, string prefix = "", int maxKeys = 100)
    {
      ViewBag.prefix = prefix;
      ViewBag.maxKeys = maxKeys;

      var list = new Amazon.S3.Model.ListObjectsRequest();
      list.WithBucketName(WebConfigurationManager.AppSettings["UploadBucket"]);
      list.WithPrefix(id);

      var s3Objects = s3.ListObjects(list).S3Objects;
      if (s3Objects.Count == 0)
      {
        return HttpNotFound();
      }


      var get = new Amazon.S3.Model.GetObjectRequest();
      get.WithBucketName(WebConfigurationManager.AppSettings["UploadBucket"]);
      get.WithKey(s3Objects[0].Key);

      var response = s3.GetObject(get);

      S3Object modelObject = new S3Object
      {
        Key = s3Objects[0].Key,
        Size = s3Objects[0].Size,
        LastModified = s3Objects[0].LastModified,
        ContentType = response.ContentType
      };

      return View(modelObject);
    }

    //
    // POST: /S3Object/Delete/5

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(string id, string prefix = "", int maxKeys = 100)
    {
      ViewBag.prefix = prefix;
      ViewBag.maxKeys = maxKeys;

      var delete = new Amazon.S3.Model.DeleteObjectRequest();
      delete.WithBucketName(WebConfigurationManager.AppSettings["UploadBucket"]);
      delete.WithKey(id);
      s3.DeleteObject(delete);
      return RedirectToAction("Index", new { prefix = prefix, maxKeys = maxKeys });
    }

    //
    // GET: /S3Object/BulkDelete

    public ActionResult BulkDelete(string prefix = "", int maxKeys = 100)
    {
      ViewBag.prefix = prefix;
      ViewBag.maxKeys = maxKeys;

      var list = new Amazon.S3.Model.ListObjectsRequest();
      list.WithBucketName(WebConfigurationManager.AppSettings["UploadBucket"]);
      if (!String.IsNullOrWhiteSpace(prefix))
      {
        list.WithPrefix(prefix);
      }

      list.WithMaxKeys(maxKeys);

      var s3Objects = s3.ListObjects(list);
      List<S3Object> modelObjects = new List<S3Object>(s3Objects.S3Objects.Count);

      foreach (var s3Object in s3Objects.S3Objects)
      {
        modelObjects.Add(new S3Object
        {
          Key = s3Object.Key,
          Size = s3Object.Size,
          LastModified = s3Object.LastModified
        });
      }

      return View(modelObjects);
    }

    [HttpPost, ActionName("BulkDelete")]
    public ActionResult BulkDeleteConfirmed(string prefix = "", int maxKeys = 100)
    {
      if (!String.IsNullOrWhiteSpace(prefix))
      {
        ViewBag.prefix = prefix;
        ViewBag.maxKeys = maxKeys;

        var list = new Amazon.S3.Model.ListObjectsRequest();
        list.WithBucketName(WebConfigurationManager.AppSettings["UploadBucket"]);
        if (!String.IsNullOrWhiteSpace(prefix))
        {
          list.WithPrefix(prefix);
        }

        list.WithMaxKeys(maxKeys);

        var keys = s3.ListObjects(list).S3Objects.Select(e => new Amazon.S3.Model.KeyVersion(e.Key)).ToArray();

        var bulkDelete = new Amazon.S3.Model.DeleteObjectsRequest();

AwsExplorer/AwsExplorer/Views/S3Object/BulkCreate.cshtml
@model AwsExplorer.Models.S3Object

@{
  ViewBag.Title = "Bulk Upload";
}

<h2>Bulk Upload</h2>

@using (Html.BeginForm("BulkCreate", "S3Object", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
  @Html.ValidationSummary(true)

  <input type="hidden" name="prefix" value="@ViewBag.prefix" />
  <input type="hidden" name="maxKeys" value="@ViewBag.maxKeys" />

  <fieldset>
    <legend>S3Object</legend>

    <div class="editor-label">
      Prefix (appended to each file name, you probably want to end it with /)
    </div>
    <div class="editor-field">
      <input type="text" name="Key" value="@ViewBag.prefix" />
    </div>

    <label>
      <span>ZIP File</span>
      <input type="file" name="Content" />
    </label>

    <p>
      <input type="submit" value="Upload" />
    </p>
  </fieldset>
}

<div>
  @Html.ActionLink("Back to List", "Index", new { prefix = ViewBag.prefix, maxKeys = ViewBag.maxKeys })
</div>

AwsExplorer/AwsExplorer/Views/S3Object/BulkDelete.cshtml
@model IEnumerable<AwsExplorer.Models.S3Object>

@{
  ViewBag.Title = "Bulk Delete";
}

<h2>Bulk Delete</h2>

@using(Html.BeginForm("BulkDelete", "S3Object", FormMethod.Get))
{
  <label>
    <span>Prefix</span>
    <input type="text" name="prefix" value="@ViewBag.prefix" />
  </label>
  
  <label>
    <span>Max Keys</span>
    <input type="number" name="maxKeys" value="@ViewBag.maxKeys" />
  </label>
  
  <button type="submit">Filter</button>
}

<p>Are you sure you want to delete these keys?</p>

<table>
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.Key)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.LastModified)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Size)
    </th>
  </tr>

  @foreach (var item in Model)
  {
    <tr>
      <td>
        @Html.DisplayFor(modelItem => item.Key)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.LastModified)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Size)
      </td>
    </tr>
  }

</table>

@using (Html.BeginForm())
{
  <input type="hidden" name="prefix" value="@ViewBag.prefix" />
  <input type="hidden" name="maxKeys" value="@ViewBag.maxKeys" />

  <p>
    <input type="submit" value="Yes, delete them all" />
    |
  @Html.ActionLink("No, back to list", "Index", new { prefix = ViewBag.prefix, maxKeys = ViewBag.maxKeys })
  </p>
}

AwsExplorer/AwsExplorer/Views/S3Object/Create.cshtml
@model AwsExplorer.Models.S3Object

@{
  ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "S3Object", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
  @Html.ValidationSummary(true)

  <input type="hidden" name="prefix" value="@ViewBag.prefix" />
  <input type="hidden" name="maxKeys" value="@ViewBag.maxKeys" />

  <fieldset>
    <legend>S3Object</legend>

    <div class="editor-label">
      Key
    </div>
    <div class="editor-field">
      <input type="text" name="Key" value="@ViewBag.prefix" />
    </div>

    <label>
      <span>File</span>
      <input type="file" name="Content" />
    </label>

    <p>
      <input type="submit" value="Create" />
    </p>
  </fieldset>
}

<div>
  @Html.ActionLink("Back to List", "Index", new { prefix = ViewBag.prefix, maxKeys = ViewBag.maxKeys })
</div>

AwsExplorer/AwsExplorer/Views/S3Object/Delete.cshtml
@model AwsExplorer.Models.S3Object

@{
  ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
  <legend>S3Object</legend>

  <div class="display-label">
    @Html.DisplayNameFor(model => model.Key)
  </div>
  <div class="display-field">
    @Html.DisplayFor(model => model.Key)
  </div>

  <div class="display-label">
    @Html.DisplayNameFor(model => model.LastModified)
  </div>
  <div class="display-field">
    @Html.DisplayFor(model => model.LastModified)
  </div>

  <div class="display-label">
    @Html.DisplayNameFor(model => model.Size)
  </div>
  <div class="display-field">
    @Html.DisplayFor(model => model.Size)
  </div>

  <div class="display-label">
    @Html.DisplayNameFor(model => model.ContentType)
  </div>
  <div class="display-field">
    @Html.DisplayFor(model => model.ContentType)
  </div>
</fieldset>
@using (Html.BeginForm())
{
  <input type="hidden" name="prefix" value="@ViewBag.prefix" />
  <input type="hidden" name="maxKeys" value="@ViewBag.maxKeys" />

  <p>
    <input type="submit" value="Delete" />
    |
  @Html.ActionLink("Back to List", "Index", new { prefix = ViewBag.prefix, maxKeys = ViewBag.maxKeys })
  </p>
}

AwsExplorer/AwsExplorer/Views/S3Object/Details.cshtml
@model AwsExplorer.Models.S3Object

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>S3Object</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Key)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Key)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastModified)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastModified)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Size)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Size)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContentType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContentType)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Key, prefix = ViewBag.prefix, maxKeys = ViewBag.maxKeys }) |
    @Html.ActionLink("Back to List", "Index", new { prefix = ViewBag.prefix, maxKeys = ViewBag.maxKeys })
</p>

AwsExplorer/AwsExplorer/Views/S3Object/Edit.cshtml
@model AwsExplorer.Models.S3Object

@{
  ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "S3Object", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
  @Html.ValidationSummary(true)

  <input type="hidden" name="prefix" value="@ViewBag.prefix" />
  <input type="hidden" name="maxKeys" value="@ViewBag.maxKeys" />

  <fieldset>
    <legend>S3Object</legend>

    <div class="display-label">
      @Html.DisplayNameFor(model => model.Key)
    </div>
    <div class="display-field">
      @Html.HiddenFor(model => model.Key)
      @Html.DisplayFor(model => model.Key)
    </div>

    <div class="display-label">
      @Html.DisplayNameFor(model => model.LastModified)
    </div>
    <div class="display-field">
      @Html.DisplayFor(model => model.LastModified)
    </div>

    <div class="display-label">
      @Html.DisplayNameFor(model => model.Size)
    </div>
    <div class="display-field">
      @Html.DisplayFor(model => model.Size)
    </div>

    <div class="display-label">
      @Html.DisplayNameFor(model => model.ContentType)
    </div>
    <div class="display-field">
      @Html.DisplayFor(model => model.ContentType)
    </div>

    <label>
      <span>New file</span>
      <input type="file" name="Content" />
    </label>

    <p>
      <input type="submit" value="Save" />
    </p>
  </fieldset>
}

<div>
  @Html.ActionLink("Back to List", "Index", new { prefix = ViewBag.prefix, maxKeys = ViewBag.maxKeys })
</div>

AwsExplorer/AwsExplorer/Views/S3Object/Index.cshtml
@model IEnumerable<AwsExplorer.Models.S3Object>

@{
  ViewBag.Title = "Index";
}

<h2>Index</h2>

@using(Html.BeginForm("Index", "S3Object", FormMethod.Get))
{
  <label>
    <span>Prefix</span>
    <input type="text" name="prefix" value="@ViewBag.prefix" />
  </label>
  
  <label>
    <span>Max Keys</span>
    <input type="number" name="maxKeys" value="@ViewBag.maxKeys" />
  </label>
  
  <button type="submit">Filter</button>
}

<p>
  @Html.ActionLink("Create New", "Create", new { prefix = ViewBag.prefix, maxKeys = ViewBag.maxKeys }) | 
  @Html.ActionLink("Bulk Upload", "BulkCreate", new { prefix = ViewBag.prefix, maxKeys = ViewBag.maxKeys }) |
  @Html.ActionLink("Bulk Delete", "BulkDelete", new { prefix = ViewBag.prefix, maxKeys = ViewBag.maxKeys })
</p>
<table>
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.Key)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.LastModified)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Size)
    </th>
    <th></th>
  </tr>

  @foreach (var item in Model)
  {
    <tr>
      <td>
        @Html.DisplayFor(modelItem => item.Key)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.LastModified)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Size)
      </td>
      <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Key, prefix = ViewBag.prefix, maxKeys = ViewBag.maxKeys }) |
            @Html.ActionLink("Details", "Details", new { id = item.Key, prefix = ViewBag.prefix, maxKeys = ViewBag.maxKeys }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Key, prefix = ViewBag.prefix, maxKeys = ViewBag.maxKeys })
      </td>
    </tr>
  }

</table>